language: php

# required for installing PHP extensions
sudo: true

php:
    - 7.2

before_install:
    # Spryker required extensions
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sudo add-apt-repository ppa:ondrej/php -y # "-y" for skipping "Enter" reuqired message
    - sudo apt-get update
    - sudo apt-get install php-gmp php-bz2

install:
    - composer install

    # prepare projects
    - bin/run prepare

script:
    - bin/run analyze
    - bin/run ecs
    - bin/run phpstan

notifications:
    email: false
