language: php

# required for installing PHP extensions
sudo: true

php:
  - 7.1

before_install:
  # Spryker required extensions
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo apt-get install php-gmp php-bz2

  # Debug: current config
  - php-config --configure-options

install:
  - composer install

  # prepare projects
  - composer download-projects

script:
  - bin/run analyze
  - bin/run ecs
  - bin/run phpstan

notifications:
  email: never
