language: php

sudo: true

php:
  - 7.1

# Spryker required extensions
before_install:
  # Redis is pre-installed on Travis, just enable it
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Add sury repo
  - sudo add-apt-repository ppa:ondrej/php -y # "-y" for skipping "Enter" reuqired message
  - sudo apt-get update

  # Install other required etensions
  - sudo apt-get install php-gmp
  - sudo apt-get install php-bz2
  # - sudo apt-get install php7.1-bcmath

  # Debug: current config
  - php-config --configure-options

install:
  - composer install

  # prepare projects
  - composer download-shopsys
  - composer download-sylius
  - composer download-spryker

script:
  # check coding standard of this project
  - composer check-cs
  - composer phpstan

  # EasyCodingStandard checks - just to test it out, it takes long time
  - composer ecs-psr2-sylius
  - composer ecs-basic-sylius

  # statistics
  - bin/run analyze
  - bin/run phpstan

notifications:
  email: never
